spring:
  application:
    name: financial-tracking-ws

# dataSource (postgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/financial-tracking-ws-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

# jpa
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# log4j
logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG

